name: bus_schedules_app

services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_DB: ${POSTGRESQL_DB}
    volumes:
      - bus_schedules_app_postgres_data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/nikolovaradica/bus-schedules-backend:latest
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${POSTGRESQL_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRESQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRESQL_PASS}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/nikolovaradica/bus-schedules-frontend:latest
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  bus_schedules_app_postgres_data: